# Generated by Django 4.2.3 on 2023-07-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavour', models.CharField(max_length=50)),
                ('ice', models.BooleanField(default=False)),
                ('nic', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('salt', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
